apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: malaria-apps-gh-runner-stage
  name: malaria-apps-gh-runner-stage
  # Namespace should already exist, created from k8s-devops repo.
  namespace: github-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: malaria-apps-gh-runner-stage
  template:
    metadata:
      labels:
        app: malaria-apps-gh-runner-stage
    spec:
      containers:
        - name: malaria-apps-gh-runner-stage
          env:
            - name: GITHUB_RUNNER_LABELS
              value: "rse-ux-stage,malaria-apps"
            - name: GITHUB_RUNNER_OWNER
              value: "InstituteforDiseaseModeling"
            - name: GITHUB_RUNNER_REPOSITORY
              value: "malaria-sle-hbhi"
          envFrom:
          # Below image, config map and secret should already exist, created from "k8s-devops" repo.
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secrets
          image: rsecr4aks.azurecr.io/rseux-gh-runner:latest
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 60
