apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: malaria-apps-sk
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
  - image: rsecr4aks.azurecr.io/malaria-bdi-hbhi
    context: ..
    kaniko:
      dockerfile: Dockerfile
      cache: {}
  cluster:
    dockerConfig:
      path: ~/.docker/config.json
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 3
        memory: 6Gi

profiles:
- name: build-docker
  build:
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
    local:
      push: false
    artifacts:
      - image: rsecr4aks.azurecr.io/malaria-bdi-hbhi
        context: ..
        docker:
          dockerfile: Dockerfile

- name: stage
  deploy:
    kustomize:
      paths:
        - "k8s/stage"
- name: prod
  deploy:
    kustomize:
      paths:
        - "k8s/prod"
