version: '3.7'
services:
  client:
    container_name: malaria-bdi-hbhi
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3838:3838"
      - "80:80"
      #- "40532-48126:40532-48126"